# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Packages addons:
#   libgdal-dev: required for rgdal package
#   libnetcdf-dev and netcdf-bin: required for ncdf4 package (based on stars travis.yml)
#   libudunits2-dev: required for units package

language: R
cache: packages
sudo: required
dist: trusty


r:
  - release
  - devel


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

warnings_are_errors: true
