# Copied over from sf/.travis.yml, and then pared down as possible
language: r

r:
  - release
  - oldrel
  - devel

warnings_are_errors: true

sudo: required
dist: trusty

cache:
  - packages
  - ccache

latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev


before_install:
  # - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'


install: R -q -e 'tic::install()'
script: R -q -e 'tic::script()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     branch: master
     condition:
       - $TRAVIS_PULL_REQUEST = false
       - $TRAVIS_EVENT_TYPE != cron
       - $TRAVIS_R_VERSION_STRING = release
