# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# https://github.com/edzer/sf_dep/blob/master/.travis.yml

language: R
cache: packages
sudo: required
dist: trusty


r:
  - release
  - devel


addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # for stars netcdf dep


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

warnings_are_errors: true
