# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Packages addons:
#   libgdal-dev: required for rgdal package
#   libnetcdf-dev and netcdf-bin: required for ncdf4 package (based on stars travis.yml)
#   libudunits2-dev: required for units package

language: R
cache: packages
sudo: required

r:
  - release
  - devel

addons:
  apt:
    packages:
      - libgdal-dev
      - libgeos-dev
      - libnetcdf-dev
      - libudunits2-dev
      - netcdf-bin

before_install:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

warnings_are_errors: true
