# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# https://github.com/edzer/sf_dep/blob/master/.travis.yml
# 'cache' changed from 'cache: packages' b/c of https://github.com/mtennekes/tmap/issues/263

language: r
cache: false
sudo: required
dist: trusty


r:
  - release
  - devel


warnings_are_errors: true


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libnetcdf-dev netcdf-bin
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'


jobs:
  include:
  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
