# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

addons:
  apt:
    packages:
      - libgdal-dev
      - libnetcdf-dev
      - libudunits2-dev
      - netcdf-bin

r:
  - release
  - devel

warnings_are_errors: true
